from pathlib import Path

path = Path('plans/reports/generate-claude-kit-map.py')
text = path.read_text(encoding='utf-8')
start = text.index("js = r'''")
end = text.index("'''.replace('__DATA__', json_for_script)", start) + len("'''.replace('__DATA__', json_for_script)")

new_js = r"""js = r'''
const DATA = __DATA__;
let currentKind = 'skill';
let currentQuery = '';
let activeName = '';
let graphState = {scale: 1, x: 0, y: 0, dragging: false, startX: 0, startY: 0, originX: 0, originY: 0};
const kinds = {skill: DATA.skills, agent: DATA.agents, command: DATA.commands};
const colors = {skill:'#34d399', agent:'#c084fc', command:'#fbbf24', other:'#94a3b8'};
function esc(value){return String(value||'').replace(/[&<>\"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function byName(kind,name){return (kinds[kind]||[]).find(item => item.name === name) || null;}
function edgeList(name){return DATA.edges.filter(edge => edge.from === name || edge.to === name);}
function setTab(kind){currentKind = kind; document.querySelectorAll('.tab').forEach(btn => btn.classList.toggle('active', btn.dataset.kind === kind)); renderList();}
function renderStats(){document.getElementById('stats').innerHTML = Object.entries(DATA.counts).map(([key,value]) => `<div class=\"card\"><div class=\"num\">${value}</div><div>${esc(key)}</div></div>`).join('');}
function renderList(){const list = document.getElementById('assetList'); const items = kinds[currentKind].filter(item => `${item.name} ${item.description} ${item.path}`.toLowerCase().includes(currentQuery)); document.getElementById('listTitle').textContent = `${currentKind}s (${items.length})`; list.innerHTML = items.map(item => `<button class=\"item ${item.name===activeName?'active':''}\" data-name=\"${esc(item.name)}\"><b>${esc(item.name)}</b><span class=\"muted\">${esc(item.description).slice(0,150)}</span><div class=\"path\">${esc(item.path)}</div></button>`).join(''); list.querySelectorAll('.item').forEach(btn => btn.addEventListener('click', () => showDetail(currentKind, btn.dataset.name)));}
function showDetail(kind,name){const item = byName(kind,name) || {name, description:'External or inferred node', path:''}; activeName = name; currentKind = kind in kinds ? kind : currentKind; const edges = edgeList(name); document.getElementById('detail').innerHTML = `<h2>${esc(item.name)}</h2><p>${esc(item.description)}</p><div class=\"path\">${esc(item.path)}</div>${item.model?`<p><b>Model:</b> ${esc(item.model)}</p>`:''}${item.tools?`<p><b>Tools:</b> ${esc(item.tools)}</p>`:''}<h3>Relationships (${edges.length})</h3><div>${edges.map(edge => `<span class=\"pill\">${esc(edge.from)} ${esc(edge.type)} ${esc(edge.to)}</span>`).join('') || '<span class=\"muted\">No direct relationship detected</span>'}</div>`; renderList(); highlightGraph(name);}
function graphNodes(){const nodes = []; DATA.commands.slice(0,28).forEach(item => nodes.push({id:item.name,type:'command'})); DATA.skills.slice(0,58).forEach(item => nodes.push({id:item.name,type:'skill'})); DATA.agents.forEach(item => nodes.push({id:item.name,type:'agent'})); return nodes;}
function applyGraphTransform(){const viewport = document.getElementById('graphViewport'); if(!viewport) return; viewport.setAttribute('transform', `translate(${graphState.x} ${graphState.y}) scale(${graphState.scale})`); document.getElementById('zoomValue').textContent = `${Math.round(graphState.scale*100)}%`;}
function zoomGraph(factor, clientX, clientY){const svg = document.getElementById('graph'); const rect = svg.getBoundingClientRect(); const viewBox = svg.viewBox.baseVal; const px = ((clientX ?? (rect.left+rect.width/2)) - rect.left) * viewBox.width / rect.width; const py = ((clientY ?? (rect.top+rect.height/2)) - rect.top) * viewBox.height / rect.height; const next = Math.max(0.35, Math.min(4, graphState.scale * factor)); const ratio = next / graphState.scale; graphState.x = px - (px - graphState.x) * ratio; graphState.y = py - (py - graphState.y) * ratio; graphState.scale = next; applyGraphTransform();}
function resetGraphZoom(){graphState = {scale:1, x:0, y:0, dragging:false, startX:0, startY:0, originX:0, originY:0}; applyGraphTransform();}
function setupGraphPanZoom(){const svg = document.getElementById('graph'); svg.addEventListener('wheel', event => {event.preventDefault(); zoomGraph(event.deltaY < 0 ? 1.12 : 0.88, event.clientX, event.clientY);}, {passive:false}); svg.addEventListener('pointerdown', event => {if(event.target.closest('.node')) return; graphState.dragging = true; graphState.startX = event.clientX; graphState.startY = event.clientY; graphState.originX = graphState.x; graphState.originY = graphState.y; svg.setPointerCapture(event.pointerId); svg.classList.add('dragging');}); svg.addEventListener('pointermove', event => {if(!graphState.dragging) return; const rect = svg.getBoundingClientRect(); const viewBox = svg.viewBox.baseVal; graphState.x = graphState.originX + (event.clientX - graphState.startX) * viewBox.width / rect.width; graphState.y = graphState.originY + (event.clientY - graphState.startY) * viewBox.height / rect.height; applyGraphTransform();}); svg.addEventListener('pointerup', event => {graphState.dragging = false; svg.classList.remove('dragging'); try{svg.releasePointerCapture(event.pointerId)}catch(_){}}); svg.addEventListener('pointerleave', () => {graphState.dragging = false; svg.classList.remove('dragging');}); document.getElementById('zoomIn').addEventListener('click', () => zoomGraph(1.2)); document.getElementById('zoomOut').addEventListener('click', () => zoomGraph(0.8)); document.getElementById('zoomReset').addEventListener('click', resetGraphZoom);}
function drawGraph(){const svg = document.getElementById('graph'); const width = 1180, height = 610, cx = width/2, cy = height/2; svg.setAttribute('viewBox', `0 0 ${width} ${height}`); svg.innerHTML = ''; const viewport = document.createElementNS('http://www.w3.org/2000/svg','g'); viewport.setAttribute('id','graphViewport'); svg.appendChild(viewport); const nodes = graphNodes(); const positions = {}; const groupConfig = {command:{r:275,y:0,start:-.5}, skill:{r:190,y:0,start:.8}, agent:{r:95,y:0,start:2.3}}; ['command','skill','agent'].forEach(type => {const group = nodes.filter(node => node.type === type); group.forEach((node,index) => {const angle = groupConfig[type].start + Math.PI*2*index/group.length; positions[node.id] = {x:cx + Math.cos(angle)*groupConfig[type].r, y:cy + Math.sin(angle)*groupConfig[type].r, type};});}); const edgeGroup = document.createElementNS('http://www.w3.org/2000/svg','g'); viewport.appendChild(edgeGroup); DATA.edges.filter(edge => positions[edge.from] && positions[edge.to]).slice(0,190).forEach(edge => {const a = positions[edge.from], b = positions[edge.to]; const line = document.createElementNS('http://www.w3.org/2000/svg','line'); line.setAttribute('x1', a.x); line.setAttribute('y1', a.y); line.setAttribute('x2', b.x); line.setAttribute('y2', b.y); line.setAttribute('class', 'edge'); line.dataset.from = edge.from; line.dataset.to = edge.to; edgeGroup.appendChild(line);}); const nodeGroup = document.createElementNS('http://www.w3.org/2000/svg','g'); viewport.appendChild(nodeGroup); nodes.forEach(node => {const pos = positions[node.id]; const g = document.createElementNS('http://www.w3.org/2000/svg','g'); g.setAttribute('class', `node ${node.type}`); g.dataset.name = node.id; g.dataset.kind = node.type; const circle = document.createElementNS('http://www.w3.org/2000/svg','circle'); circle.setAttribute('cx', pos.x); circle.setAttribute('cy', pos.y); circle.setAttribute('r', node.type === 'agent' ? 18 : 14); circle.setAttribute('fill', colors[node.type]); const text = document.createElementNS('http://www.w3.org/2000/svg','text'); text.setAttribute('x', pos.x); text.setAttribute('y', pos.y + 31); text.textContent = node.id.length > 22 ? node.id.slice(0,21)+'…' : node.id; g.appendChild(circle); g.appendChild(text); g.addEventListener('click', () => showDetail(node.type, node.id)); nodeGroup.appendChild(g);}); applyGraphTransform();}
function highlightGraph(name){document.querySelectorAll('#graph .node').forEach(node => {node.style.opacity = !name || node.dataset.name === name || edgeList(name).some(edge => edge.from === node.dataset.name || edge.to === node.dataset.name) ? '1' : '.25';}); document.querySelectorAll('#graph .edge').forEach(edge => {edge.style.opacity = !name || edge.dataset.from === name || edge.dataset.to === name ? '.9' : '.12'; edge.style.strokeWidth = edge.dataset.from === name || edge.dataset.to === name ? '2.2' : '1.1';});}
function clearHighlight(){activeName=''; highlightGraph(''); renderList();}
document.addEventListener('DOMContentLoaded', () => {renderStats(); document.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => setTab(btn.dataset.kind))); document.getElementById('search').addEventListener('input', event => {currentQuery = event.target.value.toLowerCase(); renderList();}); document.getElementById('clearGraph').addEventListener('click', clearHighlight); renderList(); drawGraph(); setupGraphPanZoom(); showDetail('skill', DATA.skills[0].name);});
'''.replace('__DATA__', json_for_script)"""

path.write_text(text[:start] + new_js + text[end:], encoding='utf-8')
